version: '3.8'

services:
  api:
    build: .
    container_name: backend_template_api
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

      DB_URI: mongodb://${DB_USER}:${DB_PASS}@mongo:27017/${DB_NAME}?authSource=admin

      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}

      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: backend_template_mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
